local addonName, NS = ...

-- LibKa0s-Launcher-1.0 seam: the minimap button and the broker plugin, as ONE object registered
-- twice (launcher-§1).
--
-- ── WHAT THIS REPLACED ────────────────────────────────────────────────────────────────────────
--
-- `B:SetupMinimap` / `B:RefreshMinimap` / `B:SetMinimapHidden` in modules/Browser.lua, ~55 lines
-- that built the LDB object, resolved LibDBIcon and registered the two by hand. Every line of it
-- was the wiring eleven addons were about to write in eleven spellings, which is what the library
-- exists to make impossible (anti-pattern #81). The click implementation moved WITH it: there was
-- one before and there is one now, and the rung rule is satisfied on the minimap and in a broker
-- display by construction rather than by two implementations agreeing.
--
-- THE REGISTRATION NAME CHANGED, and it is the one visible cost. It was the literal
-- "Ka0s Loot History"; launcher-§1 fixes it at the addon's FOLDER name, because LibDBIcon keys the
-- button by it and a broker display labels the plugin with it. The player's dragged POSITION
-- survives the rename: LibDBIcon stores `minimapPos` in the `db` table it is handed
-- (libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:194, `self.db.minimapPos`), never under the name, and the
-- table handed in is the same `NS.db.global.minimap` as before. What the rename does move is the
-- label a broker display prints, so `label` below restores the old string explicitly.
--
-- ── THE RUNG ──────────────────────────────────────────────────────────────────────────────────
--
-- (a), THE BROWSER (launcher-§2, and the standard's ADDONS.md roster records it). This addon has a
-- primary window -- the History browser -- so left-click toggles it. The rung is expressed by the
-- PRESENCE of `onClick` rather than by a flag, so it cannot be declared without being implemented.
-- Right-click ALWAYS opens the settings panel, which is what lets the left button spend itself on
-- something better.
--
-- ── LOAD ORDER ────────────────────────────────────────────────────────────────────────────────
--
-- CONVENTIONAL, not load-bearing. Nothing here resolves at load: `minimap` is a function because
-- `NS.db` does not exist yet and a table captured now is one AceDB later replaces (the library
-- resolves it at Register time), and every other field is a closure over NS.Browser / NS.Panel /
-- NS.Debug, all of which are reached long after the whole TOC has run. `Lb:Register()` is called
-- from `addon:OnInitialize`, after `NS:InitDB`, which is the first moment `NS.db.global.minimap`
-- exists.

local Launcher = LibStub and LibStub("LibKa0s-Launcher-1.0", true)

-- The ICON FILE, and it is not decoration (launcher-§4, layout-§4). `## IconTexture` in
-- LootHistory.toc names this same file, so the addon looks like itself in all three places a
-- player meets it: the AddOns list, the minimap and a broker display. A launcher whose icon file
-- is missing draws NOTHING and raises nothing (anti-pattern #82), so the path is built from
-- `addonName` rather than typed, and the file is generated by layout-§4's fixed recipe from the
-- 2000x2000 source beside it -- uncompressed 32-bit, TGA image type 2, 128x128.
NS.LAUNCHER_ICON =
  "Interface\\AddOns\\" .. addonName .. "\\media\\logos\\loothistory.logo.128.tga"

if not Launcher then
  -- Degrade by ABSENCE, which is this seam's shape rather than the stub table every other
  -- LibKa0s seam in this addon carries. The difference is real: nothing in the addon calls into
  -- this module except the two sites below, and both already guard. `core/LootHistory.lua`'s
  -- OnInitialize reaches `NS.Launcher:Register()` behind `if NS.Launcher`, and the Minimap button
  -- row's `set` in settings/Schema.lua does the same around `SetShown` -- and that row still
  -- STORES its value on this path, so a player who hides the button on a degraded install has it
  -- hidden when the library comes back. A stub answering IsShown/SetShown would be a second copy
  -- of a state that already lives in `db.global.minimap`, which is exactly the trap launcher-§3
  -- names. There is nothing to publish, so nothing is published.
  --
  -- No printed line either: core/CoreSetup.lua already says the one sentence about a missing
  -- LibKa0s once per session, and eleven seams repeating it is the noise that sentence exists to
  -- avoid.
  NS.Launcher = nil
  NS.RefreshLauncher = function() end
  return
end

NS.Launcher = Launcher:New({
  -- THE FOLDER NAME, used for BOTH registrations. Not cosmetic: see the rename note above.
  name  = addonName,
  -- What a broker display prints. Defaults to `name`, which would read "LootHistory"; this is the
  -- string the LDB object carried before the adoption, so a Titan Panel row does not rename itself.
  label = "Ka0s Loot History",
  icon  = NS.LAUNCHER_ICON,

  -- A FUNCTION, never the table: `NS.db.global.minimap` does not exist when this file loads, and a
  -- table captured at load is one AceDB replaces on InitDB. The library resolves it at Register
  -- time, which is what keeps the table LibDBIcon holds and the table the settings row writes the
  -- same table (launcher-§3).
  minimap = function() return NS.db and NS.db.global and NS.db.global.minimap end,

  -- RIGHT-click, always (launcher-§2). The same seam `/lh config` and a bare `/lh` reach.
  openSettings = function()
    if NS.Panel and NS.Panel.Open then NS.Panel:Open() end
  end,

  -- LEFT-click: RUNG (a), the primary window. `B:Toggle` is the browser's own switch -- the one
  -- `/lh toggle` calls -- so the button drives the addon's existing state rather than a copy.
  onClick = function()
    if NS.Browser and NS.Browser.Toggle then NS.Browser:Toggle() end
  end,

  -- The addon's own words, handed straight through. Unchanged from what modules/Browser.lua drew.
  onTooltipShow = function(tt)
    tt:AddLine("Ka0s Loot History", 1, 0.82, 0)
    local n = (NS.Database and NS.Database.Count) and NS.Database:Count() or 0
    tt:AddLine(n == 1 and "1 record" or (n .. " records"), 0.7, 0.7, 0.7)
    tt:AddLine(" ")
    tt:AddLine("Left-click: open the history window", 0.5, 0.5, 0.5)
    tt:AddLine("Right-click: open settings", 0.5, 0.5, 0.5)
  end,

  -- Late-bound, like every other seam's: core/LootHistory.lua reclaims NS.Print from AceConsole
  -- after this file runs, and NS.Debug is only assigned once core/DebugLogSetup.lua has.
  print = function(line) NS.Print(line) end,
  debug = function(tag, message) if NS.Debug then NS.Debug(tag, message) end end,
})

--- Hand LibDBIcon the LIVE `minimap` table again, after something replaced it.
---
--- `Sl:ResetEverything` empties `db.global` in place and merges the declared defaults back, so
--- `minimap` is a NEW table while the button still holds the old one -- and a drag before /reload
--- would store `minimapPos` in that orphan and lose the position. The library caches the table it
--- resolved at Register time in a closure local and publishes no re-point seam of its own
--- (Launcher minor 1: Register / IsRegistered / Object / IsShown / SetShown), so the call goes to
--- LibDBIcon directly, exactly as `B:RefreshMinimap` did before the adoption.
---
--- This is NOT a second copy of the button's state and not a second click implementation: it
--- re-points one registration at one table. It is the one place in this addon that still names
--- LibDBIcon, and it is named here rather than in Slash.lua so the whole launcher stays in one file.
function NS.RefreshLauncher()
  local mm = NS.db and NS.db.global and NS.db.global.minimap
  local icons = LibStub and LibStub("LibDBIcon-1.0", true)
  if mm and icons and icons:IsRegistered(addonName) then
    icons:Refresh(addonName, mm)
  end
end
