local addonName, NS = ...

-- LibKa0s-Launcher-1.0 seam: the minimap button and the broker plugin, as ONE object registered
-- twice (launcher-§1).
--
-- ── WHAT THIS REPLACED ────────────────────────────────────────────────────────────────────────
--
-- `B:SetupMinimap` / `B:RefreshMinimap` / `B:SetMinimapHidden` in modules/Browser.lua, ~55 lines
-- that built the LDB object, resolved LibDBIcon and registered the two by hand. Every line of it
-- was the wiring eleven addons were about to write in eleven spellings, which is what the library
-- exists to make impossible (anti-pattern #81). The click implementation moved WITH it: there was
-- one before and there is one now, and the two buttons (below) behave the same on the minimap and
-- in a broker display by construction rather than by two implementations agreeing.
--
-- THE REGISTRATION NAME CHANGED, and it is the one visible cost. It was the brand string
-- itself (today's NS.BRAND); launcher-§1 fixes it at the addon's FOLDER name, because LibDBIcon keys the
-- button by it and a broker display labels the plugin with it. The player's dragged POSITION
-- survives the rename: LibDBIcon stores `minimapPos` in the `db` table it is handed
-- (libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:194, `self.db.minimapPos`), never under the name, and the
-- table handed in is the same `NS.db.global.minimap` as before. What the rename does move is the
-- label a broker display prints, so `label` below restores the old string explicitly.
--
-- ── THE TWO BUTTONS ───────────────────────────────────────────────────────────────────────────
--
-- The LIBRARY's since Launcher minor 4 (LibKa0s v1.58.0; launcher-§2 as of standard v2.67.0), and
-- the same on every Ka0s addon: LEFT-click opens the settings panel, RIGHT-click opens the options
-- menu. What this file supplies is the accessor-and-toggle pair for each state the addon HAS, and
-- this addon has all four (ADDONS.md's row: Enabled · Locked · Test mode · Show window). Every
-- toggle is the addon's OWN handler -- the very function its slash verb or its settings row runs --
-- so the refusals, the combat rules and the chat lines are the addon's, and the menu holds no state.
-- The old rung (a) left-click onto the browser is now the menu's *Show window* entry.

-- ── LOAD ORDER ────────────────────────────────────────────────────────────────────────────────
--
-- CONVENTIONAL, not load-bearing. Nothing here resolves at load: `minimap` is a function because
-- `NS.db` does not exist yet and a table captured now is one AceDB later replaces (the library
-- resolves it at Register time), and every other field is a closure over NS.Browser / NS.Panel /
-- NS.Debug, all of which are reached long after the whole TOC has run. `Lb:Register()` is called
-- from `addon:OnInitialize`, after `NS:InitDB`, which is the first moment `NS.db.global.minimap`
-- exists.

local Launcher = LibStub and LibStub("LibKa0s-Launcher-1.0", true)

-- The ICON FILE, and it is not decoration (launcher-§4, layout-§4). `## IconTexture` in
-- LootHistory.toc names this same file, so the addon looks like itself in all three places a
-- player meets it: the AddOns list, the minimap and a broker display. A launcher whose icon file
-- is missing draws NOTHING and raises nothing (anti-pattern #82), so the path is built from
-- `addonName` rather than typed, and the file is generated by layout-§4's fixed recipe from the
-- 2000x2000 source beside it -- uncompressed 32-bit, TGA image type 2, 128x128.
NS.LAUNCHER_ICON =
  "Interface\\AddOns\\" .. addonName .. "\\media\\logos\\loothistory.logo.128.tga"

if not Launcher then
  -- Degrade by ABSENCE, which is this seam's shape rather than the stub table every other
  -- LibKa0s seam in this addon carries. The difference is real: nothing in the addon calls into
  -- this module except the two sites below, and both already guard. `core/LootHistory.lua`'s
  -- OnInitialize reaches `NS.Launcher:Register()` behind `if NS.Launcher`, and the Minimap button
  -- row's `set` in settings/Schema.lua does the same around `SetShown` -- and that row still
  -- STORES its value on this path, so a player who hides the button on a degraded install has it
  -- hidden when the library comes back. A stub answering IsShown/SetShown would be a second copy
  -- of a state that already lives in `db.global.minimap`, which is exactly the trap launcher-§3
  -- names. There is nothing to publish, so nothing is published.
  --
  -- No printed line either: core/CoreSetup.lua already says the one sentence about a missing
  -- LibKa0s once per session, and eleven seams repeating it is the noise that sentence exists to
  -- avoid.
  NS.Launcher = nil
  NS.RefreshLauncher = function() end
  return
end

--- Run one of the addon's own slash verbs, by name: the very function `/lh <verb>` dispatches to.
---
--- The menu's toggles call THIS rather than the model underneath (B:Toggle, CliSet, the test
--- switch), so an entry is the verb and never a copy of it (launcher-§2, anti-pattern #81): the
--- feature-verb gate settings/Schema.lua wraps round `toggle` and `test`, the confirmation line
--- `enable` prints and the refusal `test` speaks all come along. Looked up at CALL time, because
--- NS.COMMANDS is built by settings/Schema.lua, which loads after this file.
local function runVerb(verb)
  for _, entry in ipairs(NS.COMMANDS or {}) do
    if entry[1] == verb then return entry[3]("") end
  end
end

--- Whether the frames are locked: the *Lock frame* row's `settings.locked`, through B:IsLocked.
local function lockedNow()
  return (NS.Browser and NS.Browser.IsLocked and NS.Browser:IsLocked()) and true or false
end

NS.Launcher = Launcher:New({
  -- THE FOLDER NAME, used for BOTH registrations. Not cosmetic: see the rename note above.
  name  = addonName,
  -- What a broker display prints. Defaults to `name`, which would read "LootHistory"; this is the
  -- string the LDB object carried before the adoption, so a Titan Panel row does not rename itself.
  -- Read from NS.BRAND rather than typed, because slash-commands-§7's refusal line is built from
  -- the same string and an addon with two brand spellings prints the wrong one somewhere.
  label = NS.BRAND,
  icon  = NS.LAUNCHER_ICON,

  -- A FUNCTION, never the table: `NS.db.global.minimap` does not exist when this file loads, and a
  -- table captured at load is one AceDB replaces on InitDB. The library resolves it at Register
  -- time, which is what keeps the table LibDBIcon holds and the table the settings row writes the
  -- same table (launcher-§3).
  minimap = function() return NS.db and NS.db.global and NS.db.global.minimap end,

  -- LEFT-click, always and in either state (launcher-§2, Launcher minor 4). The same seam
  -- `/lh config` and a bare `/lh` reach; the right click reaches it too on a client with no
  -- context-menu API, where the library degrades to the panel.
  openSettings = function()
    if NS.Panel and NS.Panel.Open then NS.Panel:Open() end
  end,

  -- ── the options menu (right-click) ──────────────────────────────────────────────────────────
  --
  -- ENABLED: the stored switch, asked on every show and every menu open. While it answers false
  -- the library grays Locked / Test mode / Show window with "enable the addon first" and calls
  -- none of their toggles; Enabled itself stays live. `setEnabled(on)` runs the `/lh enable` or
  -- `/lh disable` verb itself -- each is `/lh set settings.enabled <bool>` through the single write
  -- seam, so the Master-controls checkbox, the verbs and the menu are three surfaces onto one value
  -- and the confirmation line is the verb's own.
  isEnabled  = function() return not (NS.AddonIsOff and NS.AddonIsOff()) end,
  setEnabled = function(on) runVerb(on and "enable" or "disable") end,

  -- LOCKED: the *Lock frame* row's `settings.locked`, read through B:IsLocked (the History
  -- window's and the export modal's own drag gate). This addon has NO lock/unlock verb, so the
  -- toggle is the ROW's own write: Schema:Set on the row's path, the seam the panel checkbox and
  -- `/lh set settings.locked` both take, so the row's onChange repaints the chrome.
  isLocked   = lockedNow,
  toggleLock = function()
    if NS.Schema and NS.Schema.Set then NS.Schema:Set("settings.locked", not lockedNow()) end
  end,

  -- TEST MODE: `state.testMode`'s get, BrowserTable.testMode, the one switch `/lh test`, the Test
  -- mode box and the combat start share. The toggle is the `/lh test` verb, so a refused start
  -- prints its own one line and a switch prints "test mode on|off", exactly as typed.
  isTestMode     = function() return NS.BrowserTable ~= nil and NS.BrowserTable.testMode == true end,
  toggleTestMode = function() runVerb("test") end,

  -- SHOW WINDOW: the History browser, this addon's primary window (standalone-windows). The toggle
  -- is the `/lh toggle` verb -- B:Toggle, routed through B:Show, so the General visibility setting
  -- refuses it with its own line exactly as it refuses the verb.
  isWindowShown = function()
    local f = NS.Browser and NS.Browser.GetWindow and NS.Browser:GetWindow()
    return (f ~= nil and f:IsShown()) and true or false
  end,
  toggleWindow = function() runVerb("toggle") end,

  -- THE STATUS TOOLTIP IS THE LIBRARY'S (Launcher minor 3, LibKa0s v1.57.0; launcher-§1). It draws
  -- on every hover, INCLUDING while the addon is disabled: `<label>  v<version>`, Enabled, Locked,
  -- Test mode (read through the accessors above), then the lines `onTooltipShow` adds, then the two
  -- fixed hints `Left-click: Open settings` and `Right-click: Options menu` (minor 4). Every field
  -- is a function because the library asks on every show and never caches.
  --
  -- The version is the TOC's (`NS.Version`, core/EnvSetup.lua), the one `/lh version` prints.
  version = function() return NS.Version and NS.Version() end,

  -- The addon's OWN line and nothing else: the record count. The title, the status and both click
  -- hints are the library's now, and drawing any of them here is a second copy (anti-pattern #89)
  -- -- which is what this hook did through Launcher minor 2, refusal line included.
  onTooltipShow = function(tt)
    local n = (NS.Database and NS.Database.Count) and NS.Database:Count() or 0
    tt:AddLine(n == 1 and "1 record" or (n .. " records"), 0.7, 0.7, 0.7)
  end,

  -- Late-bound, like every other seam's: core/LootHistory.lua reclaims NS.Print from AceConsole
  -- after this file runs, and NS.Debug is only assigned once core/DebugLogSetup.lua has.
  print = function(line) NS.Print(line) end,
  debug = function(tag, message) if NS.Debug then NS.Debug(tag, message) end end,
})

--- Hand LibDBIcon the LIVE `minimap` table again, after something replaced it.
---
--- `Sl:ResetEverything` empties `db.global` in place and merges the declared defaults back, so
--- `minimap` is a NEW table while the button still holds the old one -- and a drag before /reload
--- would store `minimapPos` in that orphan and lose the position. The library caches the table it
--- resolved at Register time in a closure local and publishes no re-point seam of its own
--- (Launcher minor 1: Register / IsRegistered / Object / IsShown / SetShown), so the call goes to
--- LibDBIcon directly, exactly as `B:RefreshMinimap` did before the adoption.
---
--- This is NOT a second copy of the button's state and not a second click implementation: it
--- re-points one registration at one table. It is the one place in this addon that still names
--- LibDBIcon, and it is named here rather than in Slash.lua so the whole launcher stays in one file.
function NS.RefreshLauncher()
  local mm = NS.db and NS.db.global and NS.db.global.minimap
  local icons = LibStub and LibStub("LibDBIcon-1.0", true)
  if mm and icons and icons:IsRegistered(addonName) then
    icons:Refresh(addonName, mm)
  end
end
